/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package desafio;

import java.util.ArrayList;

/**
 *
 * @author lgasi
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botaoNomeCadastro = new javax.swing.JButton();
        textoPesquisa = new javax.swing.JTextField();
        nomeCadrastro = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        sobrenomeCadastro = new javax.swing.JTextField();
        nomeEventoCadastro = new javax.swing.JTextField();
        lotacaoEvento = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        botaoEventoCadastro = new javax.swing.JToggleButton();
        jLabel5 = new javax.swing.JLabel();
        nomeCafeCadastro = new javax.swing.JTextField();
        lotacaoCafe = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        botaoCafeCadastro = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        nomePesquisa = new javax.swing.JTextField();
        eventoPesquisa = new javax.swing.JTextField();
        cafePesquisa = new javax.swing.JTextField();
        BotaoNomePesquisa = new javax.swing.JToggleButton();
        botaoEventoPesquisa = new javax.swing.JToggleButton();
        botaoCafePesquisa = new javax.swing.JToggleButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        botaoNomeCadastro.setText("Salvar");
        botaoNomeCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoNomeCadastroActionPerformed(evt);
            }
        });

        textoPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoPesquisaActionPerformed(evt);
            }
        });

        nomeCadrastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeCadrastroActionPerformed(evt);
            }
        });

        jLabel1.setText("Nome");

        jLabel2.setText("Sobrenome");

        jLabel3.setText("Nome da Sala");

        sobrenomeCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sobrenomeCadastroActionPerformed(evt);
            }
        });

        nomeEventoCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeEventoCadastroActionPerformed(evt);
            }
        });

        jLabel4.setText("Lotação");

        botaoEventoCadastro.setText("Salvar");
        botaoEventoCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEventoCadastroActionPerformed(evt);
            }
        });

        jLabel5.setText("Nome da Sala de Café");

        nomeCafeCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeCafeCadastroActionPerformed(evt);
            }
        });

        jLabel6.setText("Lotação");

        botaoCafeCadastro.setText("Salvar");
        botaoCafeCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCafeCadastroActionPerformed(evt);
            }
        });

        jLabel7.setText("Nome");

        nomePesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomePesquisaActionPerformed(evt);
            }
        });

        cafePesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cafePesquisaActionPerformed(evt);
            }
        });

        BotaoNomePesquisa.setText("Pesquisar");
        BotaoNomePesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoNomePesquisaActionPerformed(evt);
            }
        });

        botaoEventoPesquisa.setText("Pesquisar");
        botaoEventoPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEventoPesquisaActionPerformed(evt);
            }
        });

        botaoCafePesquisa.setText("Pesquisar");
        botaoCafePesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCafePesquisaActionPerformed(evt);
            }
        });

        jLabel8.setText("Sala");

        jLabel9.setText("Sala Café");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(96, 96, 96)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(200, 200, 200)
                        .addComponent(jLabel8)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(nomeCafeCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                                        .addComponent(nomeEventoCadastro, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(nomeCadrastro, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(sobrenomeCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lotacaoEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6)
                                    .addComponent(lotacaoCafe, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(botaoNomeCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(botaoEventoCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(botaoCafeCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nomePesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(11, 11, 11)
                                        .addComponent(BotaoNomePesquisa)))
                                .addGap(74, 74, 74)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(botaoEventoPesquisa)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(botaoCafePesquisa)
                                        .addGap(12, 12, 12))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(eventoPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(65, 65, 65)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel9)
                                                .addGap(0, 89, Short.MAX_VALUE))
                                            .addComponent(cafePesquisa))))))
                        .addGap(18, 18, 18))))
            .addComponent(textoPesquisa)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel1))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoNomeCadastro)
                    .addComponent(nomeCadrastro, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sobrenomeCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lotacaoEvento, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                        .addComponent(botaoEventoCadastro))
                    .addComponent(nomeEventoCadastro))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nomeCafeCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lotacaoCafe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(botaoCafeCadastro)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nomePesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(eventoPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cafePesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BotaoNomePesquisa)
                            .addComponent(botaoEventoPesquisa)
                            .addComponent(botaoCafePesquisa)))
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(textoPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoEventoCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEventoCadastroActionPerformed
        SalaDeEventos salaDeEventos = new SalaDeEventos(nomeEventoCadastro.getText(),Integer.valueOf(lotacaoEvento.getText()));
        listaSalaDeEventos.add(salaDeEventos);
        nomeEventoCadastro.setText("");
        lotacaoEvento.setText("");
        limpaLista();
    }//GEN-LAST:event_botaoEventoCadastroActionPerformed

    private void botaoCafeCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCafeCadastroActionPerformed
        EspacoCafe espacoCafe = new EspacoCafe(nomeCafeCadastro.getText(),Integer.getInteger(lotacaoCafe.getText()));
        listaEspacoCafe.add(espacoCafe);
        nomeCafeCadastro.setText("");
        lotacaoCafe.setText("");
        limpaLista();
    }//GEN-LAST:event_botaoCafeCadastroActionPerformed

    private void botaoEventoPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEventoPesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoEventoPesquisaActionPerformed

    private void botaoCafePesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCafePesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoCafePesquisaActionPerformed

    private void sobrenomeCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sobrenomeCadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sobrenomeCadastroActionPerformed

    private void nomeEventoCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeEventoCadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeEventoCadastroActionPerformed

    private void nomeCafeCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeCafeCadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeCafeCadastroActionPerformed

    private void cafePesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cafePesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cafePesquisaActionPerformed

    private void textoPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoPesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoPesquisaActionPerformed

    private void nomeCadrastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeCadrastroActionPerformed
        
    }//GEN-LAST:event_nomeCadrastroActionPerformed

    private void botaoNomeCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoNomeCadastroActionPerformed
        Pessoa pessoa = new Pessoa(nomeCadrastro.getText(),sobrenomeCadastro.getText());
        listaPessoa.add(pessoa);
        nomeCadrastro.setText("");
        sobrenomeCadastro.setText("");
        limpaLista();
    }//GEN-LAST:event_botaoNomeCadastroActionPerformed

    private void nomePesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomePesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomePesquisaActionPerformed

    private void BotaoNomePesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoNomePesquisaActionPerformed
        SalaDeEventos salaetapa1= null;
        for (SalaDeEventos salaDeEvento : listaSalaDeEventos) {
            for(Pessoa pessoa: salaDeEvento.getListaPessoaFase1()){
                if(pessoa.getNome().equalsIgnoreCase(nomePesquisa.getText())){
                    salaetapa1 = salaDeEvento;
                }
            }
        }
        textoPesquisa.setText(salaetapa1.getNome());
    }//GEN-LAST:event_BotaoNomePesquisaActionPerformed
    private ArrayList<SalaDeEventos> listaSalaDeEventos = new ArrayList<>();
    private ArrayList<Pessoa> listaPessoa = new ArrayList<>();
    private ArrayList<EspacoCafe> listaEspacoCafe = new ArrayList<>();
    
    
    public void limpaLista() {

        for (SalaDeEventos salaDeEvento : listaSalaDeEventos) {
            salaDeEvento.getListaPessoaFase1().clear();
            
        } for (Pessoa pessoa: listaPessoa) {
            if(getSalaComMenosPessoas()!= null){
                getSalaComMenosPessoas().getListaPessoaFase1().add(pessoa);
            }
        }
    }
        
    
    
    
    public SalaDeEventos getSalaComMenosPessoas() {
        SalaDeEventos salaComMenosPessoas = null;
        for (SalaDeEventos salaDeEvento : listaSalaDeEventos) {
            if (salaComMenosPessoas == null || salaDeEvento.getListaPessoaFase1().size() < salaComMenosPessoas.getListaPessoaFase1().size()) {
                salaComMenosPessoas = salaDeEvento;
            }
        }
        return salaComMenosPessoas;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton BotaoNomePesquisa;
    private javax.swing.JButton botaoCafeCadastro;
    private javax.swing.JToggleButton botaoCafePesquisa;
    private javax.swing.JToggleButton botaoEventoCadastro;
    private javax.swing.JToggleButton botaoEventoPesquisa;
    private javax.swing.JButton botaoNomeCadastro;
    private javax.swing.JTextField cafePesquisa;
    private javax.swing.JTextField eventoPesquisa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField lotacaoCafe;
    private javax.swing.JTextField lotacaoEvento;
    private javax.swing.JTextField nomeCadrastro;
    private javax.swing.JTextField nomeCafeCadastro;
    private javax.swing.JTextField nomeEventoCadastro;
    private javax.swing.JTextField nomePesquisa;
    private javax.swing.JTextField sobrenomeCadastro;
    private javax.swing.JTextField textoPesquisa;
    // End of variables declaration//GEN-END:variables
}
